repos:
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ../../../../miniconda3/envs/phippery/bin/pytest
      language: script
      pass_filenames: false
      types: [python]
      always_run: true
      stages: [push]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
