name: phippery
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - plotnine
  - jupyter
  - pytest
  - pytest-datadir
  - pre-commit
  - black
  - dask
  - netCDF4
  - bottleneck
  - click

